# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_elementosoPyuzp.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Elementos(object):
    def setupUi(self, Elementos):
        if not Elementos.objectName():
            Elementos.setObjectName(u"Elementos")
        Elementos.resize(1044, 581)
        self.centralwidget = QWidget(Elementos)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setStyleSheet(u"#frame{\n"
"\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0.0113636 rgba(31, 216, 210, 255), stop:1 rgba(51, 150, 255, 255));\n"
"}")
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.gridLayout_3 = QGridLayout(self.frame)
        self.gridLayout_3.setSpacing(20)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(20, 20, 20, 20)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setMaximumSize(QSize(1004, 545))
        self.frame_2.setStyleSheet(u"#frame_2{\n"
"\n"
"\n"
"\n"
"	border-radius:15px;\n"
"\n"
"\n"
"	background-color: rgba(240, 240, 240,0.7)\n"
"}")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.gridLayout_2 = QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.stackedWidget = QStackedWidget(self.frame_2)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.gridLayout_7 = QGridLayout(self.page)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.frame_5 = QFrame(self.page)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setFrameShape(QFrame.NoFrame)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.gridLayout_6 = QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.label_2 = QLabel(self.frame_5)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setMaximumSize(QSize(16777215, 40))
        self.label_2.setStyleSheet(u"font-size:25px;")
        self.label_2.setAlignment(Qt.AlignCenter)

        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)

        self.frame_6 = QFrame(self.frame_5)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setFrameShape(QFrame.NoFrame)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.lnb1 = QLineEdit(self.frame_6)
        self.lnb1.setObjectName(u"lnb1")
        self.lnb1.setGeometry(QRect(250, 60, 521, 41))
        self.lnb1.setStyleSheet(u"font-size:15px;")
        self.lnb2 = QLineEdit(self.frame_6)
        self.lnb2.setObjectName(u"lnb2")
        self.lnb2.setGeometry(QRect(250, 280, 521, 41))
        self.lnb2.setStyleSheet(u"font-size:15px;")
        self.btnb1 = QPushButton(self.frame_6)
        self.btnb1.setObjectName(u"btnb1")
        self.btnb1.setGeometry(QRect(250, 140, 160, 41))
        self.btnb3 = QPushButton(self.frame_6)
        self.btnb3.setObjectName(u"btnb3")
        self.btnb3.setGeometry(QRect(610, 140, 160, 41))
        self.btnb2 = QPushButton(self.frame_6)
        self.btnb2.setObjectName(u"btnb2")
        self.btnb2.setGeometry(QRect(430, 140, 160, 41))
        self.label_86 = QLabel(self.frame_6)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(250, 250, 111, 31))
        self.label_86.setStyleSheet(u"font-size:15px;")
        self.label_87 = QLabel(self.frame_6)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(250, 110, 111, 31))
        self.label_87.setStyleSheet(u"font-size:15px;")
        self.label_88 = QLabel(self.frame_6)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(430, 110, 111, 31))
        self.label_88.setStyleSheet(u"font-size:15px;")
        self.label_89 = QLabel(self.frame_6)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(610, 110, 111, 31))
        self.label_89.setStyleSheet(u"font-size:15px;")
        self.label_90 = QLabel(self.frame_6)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(250, 30, 111, 31))
        self.label_90.setStyleSheet(u"font-size:15px;")

        self.gridLayout_6.addWidget(self.frame_6, 1, 0, 1, 1)


        self.gridLayout_7.addWidget(self.frame_5, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.gridLayout_9 = QGridLayout(self.page_3)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.frame_7 = QFrame(self.page_3)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setFrameShape(QFrame.NoFrame)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.gridLayout_8 = QGridLayout(self.frame_7)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.label_3 = QLabel(self.frame_7)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setMinimumSize(QSize(0, 0))
        self.label_3.setMaximumSize(QSize(16777215, 40))
        self.label_3.setStyleSheet(u"font-size:25px;")
        self.label_3.setAlignment(Qt.AlignCenter)

        self.gridLayout_8.addWidget(self.label_3, 0, 0, 1, 1)

        self.frame_8 = QFrame(self.frame_7)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setFrameShape(QFrame.NoFrame)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.cboxc1 = QComboBox(self.frame_8)
        self.cboxc1.addItem("")
        self.cboxc1.addItem("")
        self.cboxc1.addItem("")
        self.cboxc1.addItem("")
        self.cboxc1.addItem("")
        self.cboxc1.addItem("")
        self.cboxc1.addItem("")
        self.cboxc1.setObjectName(u"cboxc1")
        self.cboxc1.setGeometry(QRect(50, 130, 181, 51))
        self.cboxc1.setStyleSheet(u"QComboBox{\n"
"combobox-popup: 0;\n"
"font-size:15px;\n"
"}")
        self.cboxc2 = QComboBox(self.frame_8)
        self.cboxc2.setObjectName(u"cboxc2")
        self.cboxc2.setGeometry(QRect(300, 130, 341, 51))
        self.cboxc2.setStyleSheet(u"QComboBox{\n"
"combobox-popup: 0;\n"
"font-size:15px;\n"
"}")
        self.btnc1 = QPushButton(self.frame_8)
        self.btnc1.setObjectName(u"btnc1")
        self.btnc1.setGeometry(QRect(300, 230, 160, 41))
        self.btnc2 = QPushButton(self.frame_8)
        self.btnc2.setObjectName(u"btnc2")
        self.btnc2.setGeometry(QRect(480, 230, 160, 41))
        self.btnc3 = QPushButton(self.frame_8)
        self.btnc3.setObjectName(u"btnc3")
        self.btnc3.setGeometry(QRect(300, 320, 160, 41))
        self.btnc4 = QPushButton(self.frame_8)
        self.btnc4.setObjectName(u"btnc4")
        self.btnc4.setGeometry(QRect(480, 320, 160, 41))
        self.label_80 = QLabel(self.frame_8)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(50, 100, 111, 31))
        self.label_80.setStyleSheet(u"font-size:15px;")
        self.label_81 = QLabel(self.frame_8)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(300, 100, 111, 31))
        self.label_81.setStyleSheet(u"font-size:15px;")
        self.label_82 = QLabel(self.frame_8)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(300, 200, 111, 31))
        self.label_82.setStyleSheet(u"font-size:15px;")
        self.label_83 = QLabel(self.frame_8)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(480, 200, 111, 31))
        self.label_83.setStyleSheet(u"font-size:15px;")
        self.label_84 = QLabel(self.frame_8)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(480, 290, 111, 31))
        self.label_84.setStyleSheet(u"font-size:15px;")
        self.label_85 = QLabel(self.frame_8)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(300, 290, 111, 31))
        self.label_85.setStyleSheet(u"font-size:15px;")
        self.cboxc3 = QComboBox(self.frame_8)
        self.cboxc3.setObjectName(u"cboxc3")
        self.cboxc3.setGeometry(QRect(700, 130, 241, 51))
        self.cboxc3.setStyleSheet(u"QComboBox{\n"
"combobox-popup: 0;\n"
"font-size:15px;\n"
"}")
        self.label_123 = QLabel(self.frame_8)
        self.label_123.setObjectName(u"label_123")
        self.label_123.setGeometry(QRect(700, 100, 111, 31))
        self.label_123.setStyleSheet(u"font-size:15px;")
        self.btnc5 = QPushButton(self.frame_8)
        self.btnc5.setObjectName(u"btnc5")
        self.btnc5.setGeometry(QRect(700, 230, 241, 41))
        self.label_125 = QLabel(self.frame_8)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setGeometry(QRect(700, 200, 111, 31))
        self.label_125.setStyleSheet(u"font-size:15px;")

        self.gridLayout_8.addWidget(self.frame_8, 1, 0, 1, 1)


        self.gridLayout_9.addWidget(self.frame_7, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.gridLayout_11 = QGridLayout(self.page_4)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.frame_9 = QFrame(self.page_4)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setFrameShape(QFrame.NoFrame)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.gridLayout_10 = QGridLayout(self.frame_9)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.label_4 = QLabel(self.frame_9)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setMinimumSize(QSize(0, 0))
        self.label_4.setMaximumSize(QSize(16777215, 40))
        self.label_4.setStyleSheet(u"font-size:25px;")
        self.label_4.setAlignment(Qt.AlignCenter)

        self.gridLayout_10.addWidget(self.label_4, 0, 0, 1, 1)

        self.frame_10 = QFrame(self.frame_9)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setFrameShape(QFrame.NoFrame)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.cald1 = QCalendarWidget(self.frame_10)
        self.cald1.setObjectName(u"cald1")
        self.cald1.setGeometry(QRect(220, 60, 451, 331))
        self.cald1.setFirstDayOfWeek(Qt.Monday)
        self.cald1.setGridVisible(True)
        self.cald1.setVerticalHeaderFormat(QCalendarWidget.NoVerticalHeader)
        self.btnd1 = QPushButton(self.frame_10)
        self.btnd1.setObjectName(u"btnd1")
        self.btnd1.setGeometry(QRect(700, 60, 181, 50))
        self.btnd2 = QPushButton(self.frame_10)
        self.btnd2.setObjectName(u"btnd2")
        self.btnd2.setGeometry(QRect(700, 150, 181, 50))
        self.btnd3 = QPushButton(self.frame_10)
        self.btnd3.setObjectName(u"btnd3")
        self.btnd3.setGeometry(QRect(700, 240, 181, 50))
        self.btnd4 = QPushButton(self.frame_10)
        self.btnd4.setObjectName(u"btnd4")
        self.btnd4.setGeometry(QRect(700, 340, 181, 50))
        self.label_75 = QLabel(self.frame_10)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(700, 30, 111, 31))
        self.label_75.setStyleSheet(u"font-size:15px;")
        self.label_76 = QLabel(self.frame_10)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(700, 120, 111, 31))
        self.label_76.setStyleSheet(u"font-size:15px;")
        self.label_77 = QLabel(self.frame_10)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(700, 210, 111, 31))
        self.label_77.setStyleSheet(u"font-size:15px;")
        self.label_78 = QLabel(self.frame_10)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(700, 310, 111, 31))
        self.label_78.setStyleSheet(u"font-size:15px;")
        self.label_79 = QLabel(self.frame_10)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(220, 20, 111, 31))
        self.label_79.setStyleSheet(u"font-size:15px;")

        self.gridLayout_10.addWidget(self.frame_10, 1, 0, 1, 1)


        self.gridLayout_11.addWidget(self.frame_9, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.gridLayout_13 = QGridLayout(self.page_5)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.frame_11 = QFrame(self.page_5)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setFrameShape(QFrame.NoFrame)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.gridLayout_12 = QGridLayout(self.frame_11)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.label_5 = QLabel(self.frame_11)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(0, 0))
        self.label_5.setMaximumSize(QSize(16777215, 40))
        self.label_5.setStyleSheet(u"font-size:25px;")
        self.label_5.setAlignment(Qt.AlignCenter)

        self.gridLayout_12.addWidget(self.label_5, 0, 0, 1, 1)

        self.frame_12 = QFrame(self.frame_11)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setFrameShape(QFrame.NoFrame)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.datee1 = QDateEdit(self.frame_12)
        self.datee1.setObjectName(u"datee1")
        self.datee1.setGeometry(QRect(340, 100, 291, 51))
        self.datee1.setStyleSheet(u"font-size:15px;")
        self.btne1 = QPushButton(self.frame_12)
        self.btne1.setObjectName(u"btne1")
        self.btne1.setGeometry(QRect(340, 200, 291, 51))
        self.label_73 = QLabel(self.frame_12)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(340, 70, 111, 31))
        self.label_73.setStyleSheet(u"font-size:15px;")
        self.label_74 = QLabel(self.frame_12)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(340, 170, 111, 31))
        self.label_74.setStyleSheet(u"font-size:15px;")

        self.gridLayout_12.addWidget(self.frame_12, 1, 0, 1, 1)


        self.gridLayout_13.addWidget(self.frame_11, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.gridLayout_15 = QGridLayout(self.page_6)
        self.gridLayout_15.setObjectName(u"gridLayout_15")
        self.frame_13 = QFrame(self.page_6)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setFrameShape(QFrame.NoFrame)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.gridLayout_14 = QGridLayout(self.frame_13)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.label_6 = QLabel(self.frame_13)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setMaximumSize(QSize(16777215, 40))
        self.label_6.setStyleSheet(u"font-size:25px;")
        self.label_6.setAlignment(Qt.AlignCenter)

        self.gridLayout_14.addWidget(self.label_6, 0, 0, 1, 1)

        self.frame_14 = QFrame(self.frame_13)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setFrameShape(QFrame.NoFrame)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.timef1 = QTimeEdit(self.frame_14)
        self.timef1.setObjectName(u"timef1")
        self.timef1.setGeometry(QRect(340, 90, 291, 51))
        self.timef1.setStyleSheet(u"font-size:15px;")
        self.btnf1 = QPushButton(self.frame_14)
        self.btnf1.setObjectName(u"btnf1")
        self.btnf1.setGeometry(QRect(340, 190, 291, 51))
        self.label_71 = QLabel(self.frame_14)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setGeometry(QRect(340, 60, 111, 31))
        self.label_71.setStyleSheet(u"font-size:15px;")
        self.label_72 = QLabel(self.frame_14)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(340, 160, 111, 31))
        self.label_72.setStyleSheet(u"font-size:15px;")

        self.gridLayout_14.addWidget(self.frame_14, 1, 0, 1, 1)


        self.gridLayout_15.addWidget(self.frame_13, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.gridLayout_17 = QGridLayout(self.page_7)
        self.gridLayout_17.setObjectName(u"gridLayout_17")
        self.frame_15 = QFrame(self.page_7)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setFrameShape(QFrame.NoFrame)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.gridLayout_16 = QGridLayout(self.frame_15)
        self.gridLayout_16.setObjectName(u"gridLayout_16")
        self.label_7 = QLabel(self.frame_15)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setMinimumSize(QSize(0, 0))
        self.label_7.setMaximumSize(QSize(16777215, 40))
        self.label_7.setStyleSheet(u"font-size:25px;")
        self.label_7.setAlignment(Qt.AlignCenter)

        self.gridLayout_16.addWidget(self.label_7, 0, 0, 1, 1)

        self.frame_16 = QFrame(self.frame_15)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setFrameShape(QFrame.NoFrame)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.datimeg1 = QDateTimeEdit(self.frame_16)
        self.datimeg1.setObjectName(u"datimeg1")
        self.datimeg1.setGeometry(QRect(350, 70, 361, 51))
        self.datimeg1.setStyleSheet(u"font-size:15px;")
        self.btng3 = QPushButton(self.frame_16)
        self.btng3.setObjectName(u"btng3")
        self.btng3.setGeometry(QRect(350, 260, 361, 41))
        self.btng1 = QPushButton(self.frame_16)
        self.btng1.setObjectName(u"btng1")
        self.btng1.setGeometry(QRect(350, 170, 171, 41))
        self.btng2 = QPushButton(self.frame_16)
        self.btng2.setObjectName(u"btng2")
        self.btng2.setGeometry(QRect(540, 170, 171, 41))
        self.datimeg1_2 = QLabel(self.frame_16)
        self.datimeg1_2.setObjectName(u"datimeg1_2")
        self.datimeg1_2.setGeometry(QRect(350, 40, 111, 31))
        self.datimeg1_2.setStyleSheet(u"font-size:15px;")
        self.label_68 = QLabel(self.frame_16)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setGeometry(QRect(350, 140, 111, 31))
        self.label_68.setStyleSheet(u"font-size:15px;")
        self.label_69 = QLabel(self.frame_16)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setGeometry(QRect(540, 140, 111, 31))
        self.label_69.setStyleSheet(u"font-size:15px;")
        self.label_70 = QLabel(self.frame_16)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setGeometry(QRect(350, 230, 111, 31))
        self.label_70.setStyleSheet(u"font-size:15px;")

        self.gridLayout_16.addWidget(self.frame_16, 1, 0, 1, 1)


        self.gridLayout_17.addWidget(self.frame_15, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.gridLayout_19 = QGridLayout(self.page_8)
        self.gridLayout_19.setObjectName(u"gridLayout_19")
        self.frame_17 = QFrame(self.page_8)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setFrameShape(QFrame.NoFrame)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.gridLayout_18 = QGridLayout(self.frame_17)
        self.gridLayout_18.setObjectName(u"gridLayout_18")
        self.label_8 = QLabel(self.frame_17)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setMinimumSize(QSize(0, 0))
        self.label_8.setMaximumSize(QSize(16777215, 40))
        self.label_8.setStyleSheet(u"font-size:25px;")
        self.label_8.setAlignment(Qt.AlignCenter)

        self.gridLayout_18.addWidget(self.label_8, 0, 0, 1, 1)

        self.frame_18 = QFrame(self.frame_17)
        self.frame_18.setObjectName(u"frame_18")
        self.frame_18.setFrameShape(QFrame.NoFrame)
        self.frame_18.setFrameShadow(QFrame.Raised)
        self.btnh2 = QPushButton(self.frame_18)
        self.btnh2.setObjectName(u"btnh2")
        self.btnh2.setGeometry(QRect(570, 210, 200, 50))
        self.dsboxh1 = QDoubleSpinBox(self.frame_18)
        self.dsboxh1.setObjectName(u"dsboxh1")
        self.dsboxh1.setGeometry(QRect(570, 110, 200, 41))
        self.dsboxh1.setStyleSheet(u"font-size:15px;")
        self.sboxh1 = QSpinBox(self.frame_18)
        self.sboxh1.setObjectName(u"sboxh1")
        self.sboxh1.setGeometry(QRect(220, 110, 200, 41))
        self.sboxh1.setStyleSheet(u"font-size:15px;")
        self.btnh1 = QPushButton(self.frame_18)
        self.btnh1.setObjectName(u"btnh1")
        self.btnh1.setGeometry(QRect(220, 210, 200, 50))
        self.label_63 = QLabel(self.frame_18)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(570, 70, 111, 31))
        self.label_63.setStyleSheet(u"font-size:15px;")
        self.label_64 = QLabel(self.frame_18)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(220, 70, 111, 31))
        self.label_64.setStyleSheet(u"font-size:15px;")
        self.label_65 = QLabel(self.frame_18)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(220, 180, 111, 31))
        self.label_65.setStyleSheet(u"font-size:15px;")
        self.label_66 = QLabel(self.frame_18)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(570, 180, 111, 31))
        self.label_66.setStyleSheet(u"font-size:15px;")

        self.gridLayout_18.addWidget(self.frame_18, 1, 0, 1, 1)


        self.gridLayout_19.addWidget(self.frame_17, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.gridLayout_21 = QGridLayout(self.page_9)
        self.gridLayout_21.setObjectName(u"gridLayout_21")
        self.frame_19 = QFrame(self.page_9)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setFrameShape(QFrame.NoFrame)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.gridLayout_20 = QGridLayout(self.frame_19)
        self.gridLayout_20.setObjectName(u"gridLayout_20")
        self.label_9 = QLabel(self.frame_19)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setMinimumSize(QSize(0, 0))
        self.label_9.setMaximumSize(QSize(16777215, 40))
        self.label_9.setStyleSheet(u"font-size:25px;")
        self.label_9.setAlignment(Qt.AlignCenter)

        self.gridLayout_20.addWidget(self.label_9, 0, 0, 1, 1)

        self.frame_20 = QFrame(self.frame_19)
        self.frame_20.setObjectName(u"frame_20")
        self.frame_20.setFrameShape(QFrame.NoFrame)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.ptexti1 = QPlainTextEdit(self.frame_20)
        self.ptexti1.setObjectName(u"ptexti1")
        self.ptexti1.setGeometry(QRect(250, 60, 341, 261))
        self.ptexti1.setStyleSheet(u"font-size:15px;")
        self.btni1 = QPushButton(self.frame_20)
        self.btni1.setObjectName(u"btni1")
        self.btni1.setGeometry(QRect(620, 70, 200, 50))
        self.btni2 = QPushButton(self.frame_20)
        self.btni2.setObjectName(u"btni2")
        self.btni2.setGeometry(QRect(620, 160, 200, 50))
        self.btni3 = QPushButton(self.frame_20)
        self.btni3.setObjectName(u"btni3")
        self.btni3.setGeometry(QRect(620, 260, 200, 50))
        self.label_59 = QLabel(self.frame_20)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(620, 40, 111, 31))
        self.label_59.setStyleSheet(u"font-size:15px;")
        self.label_60 = QLabel(self.frame_20)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(620, 130, 111, 31))
        self.label_60.setStyleSheet(u"font-size:15px;")
        self.label_61 = QLabel(self.frame_20)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(620, 230, 111, 31))
        self.label_61.setStyleSheet(u"font-size:15px;")
        self.label_62 = QLabel(self.frame_20)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(250, 20, 111, 31))
        self.label_62.setStyleSheet(u"font-size:15px;")

        self.gridLayout_20.addWidget(self.frame_20, 1, 0, 1, 1)


        self.gridLayout_21.addWidget(self.frame_19, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QWidget()
        self.page_10.setObjectName(u"page_10")
        self.gridLayout_23 = QGridLayout(self.page_10)
        self.gridLayout_23.setObjectName(u"gridLayout_23")
        self.frame_21 = QFrame(self.page_10)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setFrameShape(QFrame.NoFrame)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.gridLayout_22 = QGridLayout(self.frame_21)
        self.gridLayout_22.setObjectName(u"gridLayout_22")
        self.label_10 = QLabel(self.frame_21)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setMinimumSize(QSize(0, 0))
        self.label_10.setMaximumSize(QSize(16777215, 40))
        self.label_10.setStyleSheet(u"font-size:25px;")
        self.label_10.setAlignment(Qt.AlignCenter)

        self.gridLayout_22.addWidget(self.label_10, 0, 0, 1, 1)

        self.frame_22 = QFrame(self.frame_21)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setFrameShape(QFrame.NoFrame)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.hslij1 = QSlider(self.frame_22)
        self.hslij1.setObjectName(u"hslij1")
        self.hslij1.setGeometry(QRect(150, 200, 301, 41))
        self.hslij1.setMinimum(1)
        self.hslij1.setMaximum(100)
        self.hslij1.setOrientation(Qt.Horizontal)
        self.vslij1 = QSlider(self.frame_22)
        self.vslij1.setObjectName(u"vslij1")
        self.vslij1.setGeometry(QRect(620, 40, 51, 291))
        self.vslij1.setMinimum(1)
        self.vslij1.setMaximum(100)
        self.vslij1.setOrientation(Qt.Vertical)
        self.btnj2 = QPushButton(self.frame_22)
        self.btnj2.setObjectName(u"btnj2")
        self.btnj2.setGeometry(QRect(710, 170, 100, 41))
        self.btnj1 = QPushButton(self.frame_22)
        self.btnj1.setObjectName(u"btnj1")
        self.btnj1.setGeometry(QRect(150, 310, 161, 41))
        self.btnj3 = QPushButton(self.frame_22)
        self.btnj3.setObjectName(u"btnj3")
        self.btnj3.setGeometry(QRect(710, 260, 100, 41))
        self.label_54 = QLabel(self.frame_22)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(710, 120, 111, 31))
        self.label_54.setStyleSheet(u"font-size:15px;")
        self.label_55 = QLabel(self.frame_22)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(710, 230, 111, 31))
        self.label_55.setStyleSheet(u"font-size:15px;")
        self.label_56 = QLabel(self.frame_22)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(160, 270, 111, 31))
        self.label_56.setStyleSheet(u"font-size:15px;")
        self.label_57 = QLabel(self.frame_22)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(160, 150, 111, 31))
        self.label_57.setStyleSheet(u"font-size:15px;")
        self.label_58 = QLabel(self.frame_22)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(620, 330, 111, 31))
        self.label_58.setStyleSheet(u"font-size:15px;")

        self.gridLayout_22.addWidget(self.frame_22, 1, 0, 1, 1)


        self.gridLayout_23.addWidget(self.frame_21, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QWidget()
        self.page_11.setObjectName(u"page_11")
        self.gridLayout_25 = QGridLayout(self.page_11)
        self.gridLayout_25.setObjectName(u"gridLayout_25")
        self.frame_23 = QFrame(self.page_11)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setFrameShape(QFrame.NoFrame)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.gridLayout_24 = QGridLayout(self.frame_23)
        self.gridLayout_24.setObjectName(u"gridLayout_24")
        self.label_11 = QLabel(self.frame_23)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setMinimumSize(QSize(0, 0))
        self.label_11.setMaximumSize(QSize(16777215, 40))
        self.label_11.setStyleSheet(u"font-size:25px;")
        self.label_11.setAlignment(Qt.AlignCenter)

        self.gridLayout_24.addWidget(self.label_11, 0, 0, 1, 1)

        self.frame_24 = QFrame(self.frame_23)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setFrameShape(QFrame.NoFrame)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.dialk1 = QDial(self.frame_24)
        self.dialk1.setObjectName(u"dialk1")
        self.dialk1.setGeometry(QRect(330, 30, 271, 261))
        self.dialk1.setMinimum(1)
        self.dialk1.setMaximum(100)
        self.btnk1 = QPushButton(self.frame_24)
        self.btnk1.setObjectName(u"btnk1")
        self.btnk1.setGeometry(QRect(320, 350, 141, 51))
        self.btnk2 = QPushButton(self.frame_24)
        self.btnk2.setObjectName(u"btnk2")
        self.btnk2.setGeometry(QRect(480, 350, 141, 51))
        self.label_51 = QLabel(self.frame_24)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(330, 310, 111, 31))
        self.label_51.setStyleSheet(u"font-size:15px;")
        self.label_52 = QLabel(self.frame_24)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(480, 310, 111, 31))
        self.label_52.setStyleSheet(u"font-size:15px;")
        self.label_53 = QLabel(self.frame_24)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(340, 10, 111, 31))
        self.label_53.setStyleSheet(u"font-size:15px;")

        self.gridLayout_24.addWidget(self.frame_24, 1, 0, 1, 1)


        self.gridLayout_25.addWidget(self.frame_23, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QWidget()
        self.page_12.setObjectName(u"page_12")
        self.gridLayout_27 = QGridLayout(self.page_12)
        self.gridLayout_27.setObjectName(u"gridLayout_27")
        self.frame_25 = QFrame(self.page_12)
        self.frame_25.setObjectName(u"frame_25")
        self.frame_25.setFrameShape(QFrame.NoFrame)
        self.frame_25.setFrameShadow(QFrame.Raised)
        self.gridLayout_26 = QGridLayout(self.frame_25)
        self.gridLayout_26.setObjectName(u"gridLayout_26")
        self.label_12 = QLabel(self.frame_25)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setMinimumSize(QSize(0, 0))
        self.label_12.setMaximumSize(QSize(16777215, 40))
        self.label_12.setStyleSheet(u"font-size:25px;")
        self.label_12.setAlignment(Qt.AlignCenter)

        self.gridLayout_26.addWidget(self.label_12, 0, 0, 1, 1)

        self.frame_26 = QFrame(self.frame_25)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setFrameShape(QFrame.NoFrame)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.groupBox = QGroupBox(self.frame_26)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(340, 70, 201, 241))
        self.groupBox.setStyleSheet(u"font-size:15px;")
        self.rbtnl1 = QRadioButton(self.groupBox)
        self.rbtnl1.setObjectName(u"rbtnl1")
        self.rbtnl1.setGeometry(QRect(70, 60, 82, 17))
        self.rbtnl2 = QRadioButton(self.groupBox)
        self.rbtnl2.setObjectName(u"rbtnl2")
        self.rbtnl2.setGeometry(QRect(70, 110, 82, 17))
        self.rbtnl3 = QRadioButton(self.groupBox)
        self.rbtnl3.setObjectName(u"rbtnl3")
        self.rbtnl3.setGeometry(QRect(70, 160, 82, 17))
        self.label_48 = QLabel(self.frame_26)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(620, 120, 111, 31))
        self.label_48.setStyleSheet(u"font-size:15px;")
        self.label_49 = QLabel(self.frame_26)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(620, 170, 111, 31))
        self.label_49.setStyleSheet(u"font-size:15px;")
        self.label_50 = QLabel(self.frame_26)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(620, 220, 111, 31))
        self.label_50.setStyleSheet(u"font-size:15px;")

        self.gridLayout_26.addWidget(self.frame_26, 1, 0, 1, 1)


        self.gridLayout_27.addWidget(self.frame_25, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_12)
        self.page_13 = QWidget()
        self.page_13.setObjectName(u"page_13")
        self.gridLayout_29 = QGridLayout(self.page_13)
        self.gridLayout_29.setObjectName(u"gridLayout_29")
        self.frame_27 = QFrame(self.page_13)
        self.frame_27.setObjectName(u"frame_27")
        self.frame_27.setFrameShape(QFrame.NoFrame)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.gridLayout_28 = QGridLayout(self.frame_27)
        self.gridLayout_28.setObjectName(u"gridLayout_28")
        self.label_13 = QLabel(self.frame_27)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setMinimumSize(QSize(0, 0))
        self.label_13.setMaximumSize(QSize(16777215, 40))
        self.label_13.setStyleSheet(u"font-size:25px;")
        self.label_13.setAlignment(Qt.AlignCenter)

        self.gridLayout_28.addWidget(self.label_13, 0, 0, 1, 1)

        self.frame_28 = QFrame(self.frame_27)
        self.frame_28.setObjectName(u"frame_28")
        self.frame_28.setFrameShape(QFrame.NoFrame)
        self.frame_28.setFrameShadow(QFrame.Raised)
        self.groupBox_2 = QGroupBox(self.frame_28)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(350, 50, 241, 251))
        self.groupBox_2.setStyleSheet(u"font-size:15px;")
        self.chboxm1 = QCheckBox(self.groupBox_2)
        self.chboxm1.setObjectName(u"chboxm1")
        self.chboxm1.setGeometry(QRect(80, 70, 70, 17))
        self.chboxm2 = QCheckBox(self.groupBox_2)
        self.chboxm2.setObjectName(u"chboxm2")
        self.chboxm2.setGeometry(QRect(80, 110, 71, 21))
        self.chboxm3 = QCheckBox(self.groupBox_2)
        self.chboxm3.setObjectName(u"chboxm3")
        self.chboxm3.setGeometry(QRect(80, 150, 70, 17))
        self.label_45 = QLabel(self.frame_28)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(670, 100, 111, 31))
        self.label_45.setStyleSheet(u"font-size:15px;")
        self.label_46 = QLabel(self.frame_28)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(670, 150, 111, 31))
        self.label_46.setStyleSheet(u"font-size:15px;")
        self.label_47 = QLabel(self.frame_28)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(670, 200, 111, 31))
        self.label_47.setStyleSheet(u"font-size:15px;")

        self.gridLayout_28.addWidget(self.frame_28, 1, 0, 1, 1)


        self.gridLayout_29.addWidget(self.frame_27, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_13)
        self.page_14 = QWidget()
        self.page_14.setObjectName(u"page_14")
        self.gridLayout_31 = QGridLayout(self.page_14)
        self.gridLayout_31.setObjectName(u"gridLayout_31")
        self.frame_29 = QFrame(self.page_14)
        self.frame_29.setObjectName(u"frame_29")
        self.frame_29.setFrameShape(QFrame.NoFrame)
        self.frame_29.setFrameShadow(QFrame.Raised)
        self.gridLayout_30 = QGridLayout(self.frame_29)
        self.gridLayout_30.setObjectName(u"gridLayout_30")
        self.label_14 = QLabel(self.frame_29)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setMinimumSize(QSize(0, 0))
        self.label_14.setMaximumSize(QSize(16777215, 40))
        self.label_14.setStyleSheet(u"font-size:25px;")
        self.label_14.setAlignment(Qt.AlignCenter)

        self.gridLayout_30.addWidget(self.label_14, 0, 0, 1, 1)

        self.frame_30 = QFrame(self.frame_29)
        self.frame_30.setObjectName(u"frame_30")
        self.frame_30.setFrameShape(QFrame.NoFrame)
        self.frame_30.setFrameShadow(QFrame.Raised)
        self.lcdnn1 = QLCDNumber(self.frame_30)
        self.lcdnn1.setObjectName(u"lcdnn1")
        self.lcdnn1.setGeometry(QRect(300, 70, 381, 131))
        self.btnn1 = QPushButton(self.frame_30)
        self.btnn1.setObjectName(u"btnn1")
        self.btnn1.setGeometry(QRect(300, 250, 181, 61))
        self.btnn2 = QPushButton(self.frame_30)
        self.btnn2.setObjectName(u"btnn2")
        self.btnn2.setGeometry(QRect(500, 250, 181, 61))
        self.label_42 = QLabel(self.frame_30)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(300, 220, 111, 31))
        self.label_42.setStyleSheet(u"font-size:15px;")
        self.label_43 = QLabel(self.frame_30)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(500, 220, 111, 31))
        self.label_43.setStyleSheet(u"font-size:15px;")
        self.label_44 = QLabel(self.frame_30)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(300, 40, 111, 31))
        self.label_44.setStyleSheet(u"font-size:15px;")

        self.gridLayout_30.addWidget(self.frame_30, 1, 0, 1, 1)


        self.gridLayout_31.addWidget(self.frame_29, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_14)
        self.page_15 = QWidget()
        self.page_15.setObjectName(u"page_15")
        self.gridLayout_33 = QGridLayout(self.page_15)
        self.gridLayout_33.setObjectName(u"gridLayout_33")
        self.frame_31 = QFrame(self.page_15)
        self.frame_31.setObjectName(u"frame_31")
        self.frame_31.setFrameShape(QFrame.NoFrame)
        self.frame_31.setFrameShadow(QFrame.Raised)
        self.gridLayout_32 = QGridLayout(self.frame_31)
        self.gridLayout_32.setObjectName(u"gridLayout_32")
        self.label_15 = QLabel(self.frame_31)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setMinimumSize(QSize(0, 0))
        self.label_15.setMaximumSize(QSize(16777215, 40))
        self.label_15.setStyleSheet(u"font-size:25px;")
        self.label_15.setAlignment(Qt.AlignCenter)

        self.gridLayout_32.addWidget(self.label_15, 0, 0, 1, 1)

        self.frame_32 = QFrame(self.frame_31)
        self.frame_32.setObjectName(u"frame_32")
        self.frame_32.setFrameShape(QFrame.NoFrame)
        self.frame_32.setFrameShadow(QFrame.Raised)
        self.listwo1 = QListWidget(self.frame_32)
        self.listwo1.setObjectName(u"listwo1")
        self.listwo1.setGeometry(QRect(190, 40, 311, 311))
        self.btno1 = QPushButton(self.frame_32)
        self.btno1.setObjectName(u"btno1")
        self.btno1.setGeometry(QRect(530, 40, 241, 65))
        self.btno2 = QPushButton(self.frame_32)
        self.btno2.setObjectName(u"btno2")
        self.btno2.setGeometry(QRect(530, 120, 241, 65))
        self.btno3 = QPushButton(self.frame_32)
        self.btno3.setObjectName(u"btno3")
        self.btno3.setGeometry(QRect(530, 200, 241, 65))
        self.btno4 = QPushButton(self.frame_32)
        self.btno4.setObjectName(u"btno4")
        self.btno4.setGeometry(QRect(530, 290, 241, 65))
        self.label_37 = QLabel(self.frame_32)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(780, 50, 111, 31))
        self.label_37.setStyleSheet(u"font-size:15px;")
        self.label_38 = QLabel(self.frame_32)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(780, 140, 111, 31))
        self.label_38.setStyleSheet(u"font-size:15px;")
        self.label_39 = QLabel(self.frame_32)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(780, 220, 111, 31))
        self.label_39.setStyleSheet(u"font-size:15px;")
        self.label_40 = QLabel(self.frame_32)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(780, 300, 111, 31))
        self.label_40.setStyleSheet(u"font-size:15px;")
        self.label_41 = QLabel(self.frame_32)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(190, 10, 111, 31))
        self.label_41.setStyleSheet(u"font-size:15px;")

        self.gridLayout_32.addWidget(self.frame_32, 1, 0, 1, 1)


        self.gridLayout_33.addWidget(self.frame_31, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_15)
        self.page_16 = QWidget()
        self.page_16.setObjectName(u"page_16")
        self.gridLayout_35 = QGridLayout(self.page_16)
        self.gridLayout_35.setObjectName(u"gridLayout_35")
        self.frame_33 = QFrame(self.page_16)
        self.frame_33.setObjectName(u"frame_33")
        self.frame_33.setFrameShape(QFrame.NoFrame)
        self.frame_33.setFrameShadow(QFrame.Raised)
        self.gridLayout_34 = QGridLayout(self.frame_33)
        self.gridLayout_34.setObjectName(u"gridLayout_34")
        self.label_16 = QLabel(self.frame_33)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setMinimumSize(QSize(0, 0))
        self.label_16.setMaximumSize(QSize(16777215, 40))
        self.label_16.setStyleSheet(u"font-size:25px;")
        self.label_16.setAlignment(Qt.AlignCenter)

        self.gridLayout_34.addWidget(self.label_16, 0, 0, 1, 1)

        self.frame_34 = QFrame(self.frame_33)
        self.frame_34.setObjectName(u"frame_34")
        self.frame_34.setFrameShape(QFrame.NoFrame)
        self.frame_34.setFrameShadow(QFrame.Raised)
        self.stwp1 = QStackedWidget(self.frame_34)
        self.stwp1.setObjectName(u"stwp1")
        self.stwp1.setGeometry(QRect(320, 50, 441, 201))
        self.stwp1.setStyleSheet(u"QStackedWidget{\n"
"\n"
"	background-color: rgb(240, 240, 240);\n"
"}")
        self.page_22 = QWidget()
        self.page_22.setObjectName(u"page_22")
        self.frame_50 = QFrame(self.page_22)
        self.frame_50.setObjectName(u"frame_50")
        self.frame_50.setGeometry(QRect(40, 30, 371, 141))
        self.frame_50.setStyleSheet(u"\n"
"#frame_50{\n"
"background-color: rgb(234, 157, 239);\n"
"border-radius:10px;\n"
"}")
        self.frame_50.setFrameShape(QFrame.NoFrame)
        self.frame_50.setFrameShadow(QFrame.Raised)
        self.stwp1.addWidget(self.page_22)
        self.page_23 = QWidget()
        self.page_23.setObjectName(u"page_23")
        self.frame_51 = QFrame(self.page_23)
        self.frame_51.setObjectName(u"frame_51")
        self.frame_51.setGeometry(QRect(40, 30, 371, 141))
        self.frame_51.setStyleSheet(u"\n"
"#frame_51{\n"
"background-color: rgb(255, 188, 111);\n"
"border-radius:10px;\n"
"}")
        self.frame_51.setFrameShape(QFrame.NoFrame)
        self.frame_51.setFrameShadow(QFrame.Raised)
        self.stwp1.addWidget(self.page_23)
        self.btnp1 = QPushButton(self.frame_34)
        self.btnp1.setObjectName(u"btnp1")
        self.btnp1.setGeometry(QRect(320, 300, 210, 40))
        self.btnp2 = QPushButton(self.frame_34)
        self.btnp2.setObjectName(u"btnp2")
        self.btnp2.setGeometry(QRect(550, 300, 210, 40))
        self.btnp3 = QPushButton(self.frame_34)
        self.btnp3.setObjectName(u"btnp3")
        self.btnp3.setGeometry(QRect(320, 380, 441, 40))
        self.label_113 = QLabel(self.frame_34)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setGeometry(QRect(320, 10, 111, 31))
        self.label_113.setStyleSheet(u"font-size:15px;")
        self.label_114 = QLabel(self.frame_34)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setGeometry(QRect(320, 270, 111, 31))
        self.label_114.setStyleSheet(u"font-size:15px;")
        self.label_115 = QLabel(self.frame_34)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setGeometry(QRect(320, 350, 111, 31))
        self.label_115.setStyleSheet(u"font-size:15px;")
        self.label_116 = QLabel(self.frame_34)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setGeometry(QRect(550, 270, 111, 31))
        self.label_116.setStyleSheet(u"font-size:15px;")

        self.gridLayout_34.addWidget(self.frame_34, 1, 0, 1, 1)


        self.gridLayout_35.addWidget(self.frame_33, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_16)
        self.page_17 = QWidget()
        self.page_17.setObjectName(u"page_17")
        self.gridLayout_37 = QGridLayout(self.page_17)
        self.gridLayout_37.setObjectName(u"gridLayout_37")
        self.frame_35 = QFrame(self.page_17)
        self.frame_35.setObjectName(u"frame_35")
        self.frame_35.setFrameShape(QFrame.NoFrame)
        self.frame_35.setFrameShadow(QFrame.Raised)
        self.gridLayout_36 = QGridLayout(self.frame_35)
        self.gridLayout_36.setObjectName(u"gridLayout_36")
        self.label_17 = QLabel(self.frame_35)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setMinimumSize(QSize(0, 0))
        self.label_17.setMaximumSize(QSize(16777215, 40))
        self.label_17.setStyleSheet(u"font-size:25px;")
        self.label_17.setAlignment(Qt.AlignCenter)

        self.gridLayout_36.addWidget(self.label_17, 0, 0, 1, 1)

        self.frame_36 = QFrame(self.frame_35)
        self.frame_36.setObjectName(u"frame_36")
        self.frame_36.setFrameShape(QFrame.NoFrame)
        self.frame_36.setFrameShadow(QFrame.Raised)
        self.btnq3 = QPushButton(self.frame_36)
        self.btnq3.setObjectName(u"btnq3")
        self.btnq3.setGeometry(QRect(260, 390, 411, 41))
        self.btnq2 = QPushButton(self.frame_36)
        self.btnq2.setObjectName(u"btnq2")
        self.btnq2.setGeometry(QRect(480, 300, 200, 45))
        self.btnq1 = QPushButton(self.frame_36)
        self.btnq1.setObjectName(u"btnq1")
        self.btnq1.setGeometry(QRect(260, 300, 200, 45))
        self.tabq1 = QTabWidget(self.frame_36)
        self.tabq1.setObjectName(u"tabq1")
        self.tabq1.setGeometry(QRect(260, 40, 421, 211))
        self.tabq1.setStyleSheet(u"")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.frame_49 = QFrame(self.tab)
        self.frame_49.setObjectName(u"frame_49")
        self.frame_49.setGeometry(QRect(60, 30, 291, 121))
        self.frame_49.setStyleSheet(u"\n"
"#frame_49{\n"
"background-color: rgb(148, 255, 157);\n"
"border-radius:10px;\n"
"}")
        self.frame_49.setFrameShape(QFrame.NoFrame)
        self.frame_49.setFrameShadow(QFrame.Raised)
        self.btnq4 = QPushButton(self.frame_49)
        self.btnq4.setObjectName(u"btnq4")
        self.btnq4.setGeometry(QRect(90, 40, 121, 31))
        self.label_112 = QLabel(self.frame_49)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setGeometry(QRect(90, 10, 111, 31))
        self.label_112.setStyleSheet(u"font-size:15px;")
        self.tabq1.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.frame_48 = QFrame(self.tab_2)
        self.frame_48.setObjectName(u"frame_48")
        self.frame_48.setGeometry(QRect(60, 30, 291, 121))
        self.frame_48.setStyleSheet(u"\n"
"#frame_48{\n"
"background-color: rgb(255, 250, 94);\n"
"border-radius:10px;\n"
"}")
        self.frame_48.setFrameShape(QFrame.NoFrame)
        self.frame_48.setFrameShadow(QFrame.Raised)
        self.tabq1.addTab(self.tab_2, "")
        self.label_108 = QLabel(self.frame_36)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(260, 270, 111, 31))
        self.label_108.setStyleSheet(u"font-size:15px;")
        self.label_109 = QLabel(self.frame_36)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(260, 360, 111, 31))
        self.label_109.setStyleSheet(u"font-size:15px;")
        self.label_110 = QLabel(self.frame_36)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(480, 270, 111, 31))
        self.label_110.setStyleSheet(u"font-size:15px;")
        self.label_111 = QLabel(self.frame_36)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(260, 10, 111, 31))
        self.label_111.setStyleSheet(u"font-size:15px;")

        self.gridLayout_36.addWidget(self.frame_36, 1, 0, 1, 1)


        self.gridLayout_37.addWidget(self.frame_35, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_17)
        self.page_18 = QWidget()
        self.page_18.setObjectName(u"page_18")
        self.gridLayout_39 = QGridLayout(self.page_18)
        self.gridLayout_39.setObjectName(u"gridLayout_39")
        self.frame_37 = QFrame(self.page_18)
        self.frame_37.setObjectName(u"frame_37")
        self.frame_37.setFrameShape(QFrame.NoFrame)
        self.frame_37.setFrameShadow(QFrame.Raised)
        self.gridLayout_38 = QGridLayout(self.frame_37)
        self.gridLayout_38.setObjectName(u"gridLayout_38")
        self.label_18 = QLabel(self.frame_37)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setMinimumSize(QSize(0, 0))
        self.label_18.setMaximumSize(QSize(16777215, 40))
        self.label_18.setStyleSheet(u"font-size:25px;")
        self.label_18.setAlignment(Qt.AlignCenter)

        self.gridLayout_38.addWidget(self.label_18, 0, 0, 1, 1)

        self.frame_38 = QFrame(self.frame_37)
        self.frame_38.setObjectName(u"frame_38")
        self.frame_38.setFrameShape(QFrame.NoFrame)
        self.frame_38.setFrameShadow(QFrame.Raised)
        self.tboxr1 = QToolBox(self.frame_38)
        self.tboxr1.setObjectName(u"tboxr1")
        self.tboxr1.setGeometry(QRect(130, 70, 421, 331))
        self.tboxr1.setStyleSheet(u"QToolBox{\n"
"	background-color: #f0f0f0\n"
"\n"
"\n"
"}")
        self.page_24 = QWidget()
        self.page_24.setObjectName(u"page_24")
        self.page_24.setGeometry(QRect(0, 0, 421, 250))
        self.frame_45 = QFrame(self.page_24)
        self.frame_45.setObjectName(u"frame_45")
        self.frame_45.setGeometry(QRect(30, 20, 361, 191))
        self.frame_45.setStyleSheet(u"\n"
"#frame_45{\n"
"background-color: rgb(146, 255, 146);\n"
"border-radius:10px;\n"
"}")
        self.frame_45.setFrameShape(QFrame.NoFrame)
        self.frame_45.setFrameShadow(QFrame.Raised)
        self.btnr5 = QPushButton(self.frame_45)
        self.btnr5.setObjectName(u"btnr5")
        self.btnr5.setGeometry(QRect(90, 70, 181, 41))
        self.label_107 = QLabel(self.frame_45)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(90, 40, 111, 31))
        self.label_107.setStyleSheet(u"font-size:15px;")
        self.tboxr1.addItem(self.page_24, u"Page 1")
        self.page_25 = QWidget()
        self.page_25.setObjectName(u"page_25")
        self.page_25.setGeometry(QRect(0, 0, 100, 30))
        self.frame_46 = QFrame(self.page_25)
        self.frame_46.setObjectName(u"frame_46")
        self.frame_46.setGeometry(QRect(30, 20, 361, 191))
        self.frame_46.setStyleSheet(u"\n"
"#frame_46{\n"
"background-color: rgb(255, 250, 94);\n"
"border-radius:10px;\n"
"}")
        self.frame_46.setFrameShape(QFrame.NoFrame)
        self.frame_46.setFrameShadow(QFrame.Raised)
        self.tboxr1.addItem(self.page_25, u"Page 2")
        self.page_26 = QWidget()
        self.page_26.setObjectName(u"page_26")
        self.page_26.setGeometry(QRect(0, 0, 100, 30))
        self.frame_47 = QFrame(self.page_26)
        self.frame_47.setObjectName(u"frame_47")
        self.frame_47.setGeometry(QRect(20, 20, 361, 191))
        self.frame_47.setStyleSheet(u"\n"
"#frame_47{\n"
"	background-color: rgb(255, 129, 242);\n"
"border-radius:10px;\n"
"}")
        self.frame_47.setFrameShape(QFrame.NoFrame)
        self.frame_47.setFrameShadow(QFrame.Raised)
        self.tboxr1.addItem(self.page_26, u"Page 3")
        self.btnr1 = QPushButton(self.frame_38)
        self.btnr1.setObjectName(u"btnr1")
        self.btnr1.setGeometry(QRect(610, 80, 200, 45))
        self.btnr4 = QPushButton(self.frame_38)
        self.btnr4.setObjectName(u"btnr4")
        self.btnr4.setGeometry(QRect(610, 350, 200, 45))
        self.btnr2 = QPushButton(self.frame_38)
        self.btnr2.setObjectName(u"btnr2")
        self.btnr2.setGeometry(QRect(610, 170, 200, 45))
        self.btnr3 = QPushButton(self.frame_38)
        self.btnr3.setObjectName(u"btnr3")
        self.btnr3.setGeometry(QRect(610, 260, 200, 45))
        self.label_102 = QLabel(self.frame_38)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(610, 50, 111, 31))
        self.label_102.setStyleSheet(u"font-size:15px;")
        self.label_103 = QLabel(self.frame_38)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(610, 140, 111, 31))
        self.label_103.setStyleSheet(u"font-size:15px;")
        self.label_104 = QLabel(self.frame_38)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(610, 230, 111, 31))
        self.label_104.setStyleSheet(u"font-size:15px;")
        self.label_105 = QLabel(self.frame_38)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(610, 320, 111, 31))
        self.label_105.setStyleSheet(u"font-size:15px;")
        self.label_106 = QLabel(self.frame_38)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(130, 30, 111, 31))
        self.label_106.setStyleSheet(u"font-size:15px;")
        self.btnr1.raise_()
        self.btnr4.raise_()
        self.btnr2.raise_()
        self.btnr3.raise_()
        self.label_102.raise_()
        self.tboxr1.raise_()
        self.label_103.raise_()
        self.label_104.raise_()
        self.label_105.raise_()
        self.label_106.raise_()

        self.gridLayout_38.addWidget(self.frame_38, 1, 0, 1, 1)


        self.gridLayout_39.addWidget(self.frame_37, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_18)
        self.page_19 = QWidget()
        self.page_19.setObjectName(u"page_19")
        self.gridLayout_41 = QGridLayout(self.page_19)
        self.gridLayout_41.setObjectName(u"gridLayout_41")
        self.frame_39 = QFrame(self.page_19)
        self.frame_39.setObjectName(u"frame_39")
        self.frame_39.setFrameShape(QFrame.NoFrame)
        self.frame_39.setFrameShadow(QFrame.Raised)
        self.gridLayout_40 = QGridLayout(self.frame_39)
        self.gridLayout_40.setObjectName(u"gridLayout_40")
        self.label_19 = QLabel(self.frame_39)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setMinimumSize(QSize(0, 0))
        self.label_19.setMaximumSize(QSize(16777215, 40))
        self.label_19.setStyleSheet(u"font-size:25px;")
        self.label_19.setAlignment(Qt.AlignCenter)

        self.gridLayout_40.addWidget(self.label_19, 0, 0, 1, 1)

        self.frame_40 = QFrame(self.frame_39)
        self.frame_40.setObjectName(u"frame_40")
        self.frame_40.setFrameShape(QFrame.NoFrame)
        self.frame_40.setFrameShadow(QFrame.Raised)
        self.bars1 = QProgressBar(self.frame_40)
        self.bars1.setObjectName(u"bars1")
        self.bars1.setGeometry(QRect(280, 110, 521, 41))
        self.bars1.setValue(30)
        self.bars1.setOrientation(Qt.Horizontal)
        self.btns1 = QPushButton(self.frame_40)
        self.btns1.setObjectName(u"btns1")
        self.btns1.setGeometry(QRect(280, 210, 150, 45))
        self.btns3 = QPushButton(self.frame_40)
        self.btns3.setObjectName(u"btns3")
        self.btns3.setGeometry(QRect(620, 210, 150, 45))
        self.btns2 = QPushButton(self.frame_40)
        self.btns2.setObjectName(u"btns2")
        self.btns2.setGeometry(QRect(450, 210, 150, 45))
        self.label_98 = QLabel(self.frame_40)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(280, 80, 111, 31))
        self.label_98.setStyleSheet(u"font-size:15px;")
        self.label_99 = QLabel(self.frame_40)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(280, 180, 111, 31))
        self.label_99.setStyleSheet(u"font-size:15px;")
        self.label_100 = QLabel(self.frame_40)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(460, 180, 111, 31))
        self.label_100.setStyleSheet(u"font-size:15px;")
        self.label_101 = QLabel(self.frame_40)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(620, 180, 111, 31))
        self.label_101.setStyleSheet(u"font-size:15px;")

        self.gridLayout_40.addWidget(self.frame_40, 1, 0, 1, 1)


        self.gridLayout_41.addWidget(self.frame_39, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_19)
        self.page_20 = QWidget()
        self.page_20.setObjectName(u"page_20")
        self.gridLayout_43 = QGridLayout(self.page_20)
        self.gridLayout_43.setObjectName(u"gridLayout_43")
        self.frame_41 = QFrame(self.page_20)
        self.frame_41.setObjectName(u"frame_41")
        self.frame_41.setFrameShape(QFrame.NoFrame)
        self.frame_41.setFrameShadow(QFrame.Raised)
        self.gridLayout_42 = QGridLayout(self.frame_41)
        self.gridLayout_42.setObjectName(u"gridLayout_42")
        self.label_20 = QLabel(self.frame_41)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setMinimumSize(QSize(0, 0))
        self.label_20.setMaximumSize(QSize(16777215, 40))
        self.label_20.setStyleSheet(u"font-size:25px;")
        self.label_20.setAlignment(Qt.AlignCenter)

        self.gridLayout_42.addWidget(self.label_20, 0, 0, 1, 1)

        self.frame_42 = QFrame(self.frame_41)
        self.frame_42.setObjectName(u"frame_42")
        self.frame_42.setFrameShape(QFrame.NoFrame)
        self.frame_42.setFrameShadow(QFrame.Raised)
        self.tablet1 = QTableWidget(self.frame_42)
        if (self.tablet1.columnCount() < 4):
            self.tablet1.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.tablet1.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tablet1.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tablet1.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tablet1.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tablet1.setObjectName(u"tablet1")
        self.tablet1.setGeometry(QRect(210, 50, 541, 231))
        self.tablet1.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tablet1.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tablet1.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tablet1.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tablet1.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tablet1.horizontalHeader().setHighlightSections(False)
        self.tablet1.verticalHeader().setHighlightSections(False)
        self.btnt1 = QPushButton(self.frame_42)
        self.btnt1.setObjectName(u"btnt1")
        self.btnt1.setGeometry(QRect(210, 330, 120, 51))
        self.btnt2 = QPushButton(self.frame_42)
        self.btnt2.setObjectName(u"btnt2")
        self.btnt2.setGeometry(QRect(350, 330, 120, 51))
        self.btnt3 = QPushButton(self.frame_42)
        self.btnt3.setObjectName(u"btnt3")
        self.btnt3.setGeometry(QRect(490, 330, 120, 51))
        self.btnt4 = QPushButton(self.frame_42)
        self.btnt4.setObjectName(u"btnt4")
        self.btnt4.setGeometry(QRect(630, 330, 120, 51))
        self.label_93 = QLabel(self.frame_42)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(210, 300, 111, 31))
        self.label_93.setStyleSheet(u"font-size:15px;")
        self.label_94 = QLabel(self.frame_42)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(350, 300, 111, 31))
        self.label_94.setStyleSheet(u"font-size:15px;")
        self.label_95 = QLabel(self.frame_42)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(490, 300, 111, 31))
        self.label_95.setStyleSheet(u"font-size:15px;")
        self.label_96 = QLabel(self.frame_42)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(630, 300, 111, 31))
        self.label_96.setStyleSheet(u"font-size:15px;")
        self.label_97 = QLabel(self.frame_42)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(210, 20, 111, 31))
        self.label_97.setStyleSheet(u"font-size:15px;")

        self.gridLayout_42.addWidget(self.frame_42, 1, 0, 1, 1)


        self.gridLayout_43.addWidget(self.frame_41, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_20)
        self.page_21 = QWidget()
        self.page_21.setObjectName(u"page_21")
        self.gridLayout_45 = QGridLayout(self.page_21)
        self.gridLayout_45.setObjectName(u"gridLayout_45")
        self.frame_43 = QFrame(self.page_21)
        self.frame_43.setObjectName(u"frame_43")
        self.frame_43.setFrameShape(QFrame.NoFrame)
        self.frame_43.setFrameShadow(QFrame.Raised)
        self.gridLayout_44 = QGridLayout(self.frame_43)
        self.gridLayout_44.setObjectName(u"gridLayout_44")
        self.label_21 = QLabel(self.frame_43)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setMinimumSize(QSize(0, 0))
        self.label_21.setMaximumSize(QSize(16777215, 40))
        self.label_21.setStyleSheet(u"font-size:25px;")
        self.label_21.setAlignment(Qt.AlignCenter)

        self.gridLayout_44.addWidget(self.label_21, 0, 0, 1, 1)

        self.frame_44 = QFrame(self.frame_43)
        self.frame_44.setObjectName(u"frame_44")
        self.frame_44.setFrameShape(QFrame.NoFrame)
        self.frame_44.setFrameShadow(QFrame.Raised)
        self.fcboxu1 = QFontComboBox(self.frame_44)
        self.fcboxu1.setObjectName(u"fcboxu1")
        self.fcboxu1.setGeometry(QRect(280, 200, 371, 41))
        self.fcboxu1.setStyleSheet(u"font-size:15px;")
        self.btnu1 = QPushButton(self.frame_44)
        self.btnu1.setObjectName(u"btnu1")
        self.btnu1.setGeometry(QRect(280, 310, 371, 41))
        self.lblu1 = QLabel(self.frame_44)
        self.lblu1.setObjectName(u"lblu1")
        self.lblu1.setGeometry(QRect(260, 70, 421, 61))
        self.lblu1.setStyleSheet(u"font-size:25px;")
        self.lblu1.setAlignment(Qt.AlignCenter)
        self.label_117 = QLabel(self.frame_44)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(280, 170, 111, 31))
        self.label_117.setStyleSheet(u"font-size:15px;")
        self.label_118 = QLabel(self.frame_44)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(280, 280, 111, 31))
        self.label_118.setStyleSheet(u"font-size:15px;")
        self.label_119 = QLabel(self.frame_44)
        self.label_119.setObjectName(u"label_119")
        self.label_119.setGeometry(QRect(280, 40, 111, 31))
        self.label_119.setStyleSheet(u"font-size:15px;")

        self.gridLayout_44.addWidget(self.frame_44, 1, 0, 1, 1)


        self.gridLayout_45.addWidget(self.frame_43, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_21)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.gridLayout_5 = QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.frame_3 = QFrame(self.page_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.gridLayout_4 = QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.label = QLabel(self.frame_3)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(0, 0))
        self.label.setMaximumSize(QSize(16777215, 40))
        self.label.setStyleSheet(u"font-size:25px;")
        self.label.setAlignment(Qt.AlignCenter)

        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)

        self.frame_4 = QFrame(self.frame_3)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.btna1 = QPushButton(self.frame_4)
        self.btna1.setObjectName(u"btna1")
        self.btna1.setGeometry(QRect(190, 140, 291, 71))
        self.btna2 = QPushButton(self.frame_4)
        self.btna2.setObjectName(u"btna2")
        self.btna2.setGeometry(QRect(520, 140, 301, 71))
        self.label_91 = QLabel(self.frame_4)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(190, 110, 111, 31))
        self.label_91.setStyleSheet(u"font-size:15px;")
        self.label_92 = QLabel(self.frame_4)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(520, 110, 111, 31))
        self.label_92.setStyleSheet(u"font-size:15px;")

        self.gridLayout_4.addWidget(self.frame_4, 1, 0, 1, 1)


        self.gridLayout_5.addWidget(self.frame_3, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_2)
        self.page_27 = QWidget()
        self.page_27.setObjectName(u"page_27")
        self.gridLayout_47 = QGridLayout(self.page_27)
        self.gridLayout_47.setObjectName(u"gridLayout_47")
        self.frame_52 = QFrame(self.page_27)
        self.frame_52.setObjectName(u"frame_52")
        self.frame_52.setFrameShape(QFrame.NoFrame)
        self.frame_52.setFrameShadow(QFrame.Raised)
        self.gridLayout_46 = QGridLayout(self.frame_52)
        self.gridLayout_46.setObjectName(u"gridLayout_46")
        self.label_22 = QLabel(self.frame_52)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setMinimumSize(QSize(0, 0))
        self.label_22.setMaximumSize(QSize(16777215, 40))
        self.label_22.setStyleSheet(u"font-size:25px;")
        self.label_22.setAlignment(Qt.AlignCenter)

        self.gridLayout_46.addWidget(self.label_22, 0, 0, 1, 1)

        self.frame_53 = QFrame(self.frame_52)
        self.frame_53.setObjectName(u"frame_53")
        self.frame_53.setFrameShape(QFrame.NoFrame)
        self.frame_53.setFrameShadow(QFrame.Raised)
        self.label_120 = QLabel(self.frame_53)
        self.label_120.setObjectName(u"label_120")
        self.label_120.setGeometry(QRect(510, 370, 111, 31))
        self.label_120.setStyleSheet(u"font-size:15px;")
        self.label_121 = QLabel(self.frame_53)
        self.label_121.setObjectName(u"label_121")
        self.label_121.setGeometry(QRect(340, 370, 111, 31))
        self.label_121.setStyleSheet(u"font-size:15px;")
        self.sareav1 = QScrollArea(self.frame_53)
        self.sareav1.setObjectName(u"sareav1")
        self.sareav1.setGeometry(QRect(340, 70, 311, 281))
        self.sareav1.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 292, 618))
        self.gridLayout_48 = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_48.setObjectName(u"gridLayout_48")
        self.frame_54 = QFrame(self.scrollAreaWidgetContents)
        self.frame_54.setObjectName(u"frame_54")
        self.frame_54.setMinimumSize(QSize(0, 600))
        self.frame_54.setFrameShape(QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QFrame.Raised)
        self.label_23 = QLabel(self.frame_54)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(20, 20, 81, 31))
        self.lineEdit = QLineEdit(self.frame_54)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(20, 50, 241, 31))
        self.label_24 = QLabel(self.frame_54)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 110, 81, 31))
        self.lineEdit_2 = QLineEdit(self.frame_54)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(20, 150, 241, 31))
        self.label_25 = QLabel(self.frame_54)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 200, 81, 31))
        self.lineEdit_3 = QLineEdit(self.frame_54)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(20, 240, 241, 31))
        self.label_26 = QLabel(self.frame_54)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 290, 81, 31))
        self.plainTextEdit = QPlainTextEdit(self.frame_54)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(20, 330, 241, 161))
        self.spinBox = QSpinBox(self.frame_54)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(20, 540, 241, 31))
        self.spinBox.setValue(1)
        self.label_27 = QLabel(self.frame_54)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(20, 510, 81, 31))

        self.gridLayout_48.addWidget(self.frame_54, 0, 0, 1, 1)

        self.sareav1.setWidget(self.scrollAreaWidgetContents)
        self.btnv1 = QPushButton(self.frame_53)
        self.btnv1.setObjectName(u"btnv1")
        self.btnv1.setGeometry(QRect(340, 400, 151, 31))
        self.btnv2 = QPushButton(self.frame_53)
        self.btnv2.setObjectName(u"btnv2")
        self.btnv2.setGeometry(QRect(510, 400, 141, 31))
        self.label_122 = QLabel(self.frame_53)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setGeometry(QRect(340, 30, 111, 31))
        self.label_122.setStyleSheet(u"font-size:15px;")

        self.gridLayout_46.addWidget(self.frame_53, 1, 0, 1, 1)


        self.gridLayout_47.addWidget(self.frame_52, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_27)
        self.page_28 = QWidget()
        self.page_28.setObjectName(u"page_28")
        self.gridLayout_50 = QGridLayout(self.page_28)
        self.gridLayout_50.setObjectName(u"gridLayout_50")
        self.frame_55 = QFrame(self.page_28)
        self.frame_55.setObjectName(u"frame_55")
        self.frame_55.setFrameShape(QFrame.NoFrame)
        self.frame_55.setFrameShadow(QFrame.Raised)
        self.gridLayout_49 = QGridLayout(self.frame_55)
        self.gridLayout_49.setObjectName(u"gridLayout_49")
        self.label_28 = QLabel(self.frame_55)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setMinimumSize(QSize(0, 0))
        self.label_28.setMaximumSize(QSize(16777215, 40))
        self.label_28.setStyleSheet(u"font-size:25px;")
        self.label_28.setAlignment(Qt.AlignCenter)

        self.gridLayout_49.addWidget(self.label_28, 0, 0, 1, 1)

        self.frame_56 = QFrame(self.frame_55)
        self.frame_56.setObjectName(u"frame_56")
        self.frame_56.setFrameShape(QFrame.NoFrame)
        self.frame_56.setFrameShadow(QFrame.Raised)
        self.label_124 = QLabel(self.frame_56)
        self.label_124.setObjectName(u"label_124")
        self.label_124.setGeometry(QRect(370, 260, 111, 31))
        self.label_124.setStyleSheet(u"font-size:15px;")
        self.btnw1 = QPushButton(self.frame_56)
        self.btnw1.setObjectName(u"btnw1")
        self.btnw1.setGeometry(QRect(370, 290, 231, 51))
        self.lblw1 = QLabel(self.frame_56)
        self.lblw1.setObjectName(u"lblw1")
        self.lblw1.setGeometry(QRect(310, 100, 351, 101))
        self.lblw1.setStyleSheet(u"font-size:35px;")
        self.lblw1.setAlignment(Qt.AlignCenter)

        self.gridLayout_49.addWidget(self.frame_56, 1, 0, 1, 1)


        self.gridLayout_50.addWidget(self.frame_55, 0, 0, 1, 1)

        self.stackedWidget.addWidget(self.page_28)

        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)


        self.gridLayout_3.addWidget(self.frame_2, 0, 1, 1, 1)


        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        Elementos.setCentralWidget(self.centralwidget)

        self.retranslateUi(Elementos)

        self.stackedWidget.setCurrentIndex(1)
        self.stwp1.setCurrentIndex(0)
        self.tabq1.setCurrentIndex(0)
        self.tboxr1.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Elementos)
    # setupUi

    def retranslateUi(self, Elementos):
        Elementos.setWindowTitle(QCoreApplication.translate("Elementos", u"Elementos - ALEX7320", None))
        self.label_2.setText(QCoreApplication.translate("Elementos", u"QLineEdit", None))
        self.lnb1.setText(QCoreApplication.translate("Elementos", u"texto inicial", None))
        self.btnb1.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.btnb3.setText(QCoreApplication.translate("Elementos", u"clear", None))
        self.btnb2.setText(QCoreApplication.translate("Elementos", u"add", None))
        self.label_86.setText(QCoreApplication.translate("Elementos", u"lnb2", None))
        self.label_87.setText(QCoreApplication.translate("Elementos", u"btnb1", None))
        self.label_88.setText(QCoreApplication.translate("Elementos", u"btnb2", None))
        self.label_89.setText(QCoreApplication.translate("Elementos", u"btnb3", None))
        self.label_90.setText(QCoreApplication.translate("Elementos", u"lnb1", None))
        self.label_3.setText(QCoreApplication.translate("Elementos", u"QComboBox", None))
        self.cboxc1.setItemText(0, QCoreApplication.translate("Elementos", u"python", None))
        self.cboxc1.setItemText(1, QCoreApplication.translate("Elementos", u"c++", None))
        self.cboxc1.setItemText(2, QCoreApplication.translate("Elementos", u"java", None))
        self.cboxc1.setItemText(3, QCoreApplication.translate("Elementos", u"html", None))
        self.cboxc1.setItemText(4, QCoreApplication.translate("Elementos", u"css", None))
        self.cboxc1.setItemText(5, QCoreApplication.translate("Elementos", u"pearl", None))
        self.cboxc1.setItemText(6, QCoreApplication.translate("Elementos", u"r", None))

        self.btnc1.setText(QCoreApplication.translate("Elementos", u"Agregar elementos", None))
        self.btnc2.setText(QCoreApplication.translate("Elementos", u"Agregar un elemento", None))
        self.btnc3.setText(QCoreApplication.translate("Elementos", u"Borrar elementos", None))
        self.btnc4.setText(QCoreApplication.translate("Elementos", u"Borrar un elemento", None))
        self.label_80.setText(QCoreApplication.translate("Elementos", u"cboxc1", None))
        self.label_81.setText(QCoreApplication.translate("Elementos", u"cboxc2", None))
        self.label_82.setText(QCoreApplication.translate("Elementos", u"btnc1", None))
        self.label_83.setText(QCoreApplication.translate("Elementos", u"btnc2", None))
        self.label_84.setText(QCoreApplication.translate("Elementos", u"btnc4", None))
        self.label_85.setText(QCoreApplication.translate("Elementos", u"btnc3", None))
        self.label_123.setText(QCoreApplication.translate("Elementos", u"cboxc3", None))
        self.btnc5.setText(QCoreApplication.translate("Elementos", u"Get Item", None))
        self.label_125.setText(QCoreApplication.translate("Elementos", u"btnc5", None))
        self.label_4.setText(QCoreApplication.translate("Elementos", u"QCalendarWidget", None))
        self.btnd1.setText(QCoreApplication.translate("Elementos", u"mes anterior", None))
        self.btnd2.setText(QCoreApplication.translate("Elementos", u"mes siguiente", None))
        self.btnd3.setText(QCoreApplication.translate("Elementos", u"a\u00f1o siguiente", None))
        self.btnd4.setText(QCoreApplication.translate("Elementos", u"a\u00f1o anterior", None))
        self.label_75.setText(QCoreApplication.translate("Elementos", u"btnd1", None))
        self.label_76.setText(QCoreApplication.translate("Elementos", u"btnd2", None))
        self.label_77.setText(QCoreApplication.translate("Elementos", u"btnd3", None))
        self.label_78.setText(QCoreApplication.translate("Elementos", u"btnd4", None))
        self.label_79.setText(QCoreApplication.translate("Elementos", u"cald1", None))
        self.label_5.setText(QCoreApplication.translate("Elementos", u"QDateEdit", None))
        self.btne1.setText(QCoreApplication.translate("Elementos", u"get date", None))
        self.label_73.setText(QCoreApplication.translate("Elementos", u"datee1", None))
        self.label_74.setText(QCoreApplication.translate("Elementos", u"btne1", None))
        self.label_6.setText(QCoreApplication.translate("Elementos", u"QTimeEdit", None))
        self.btnf1.setText(QCoreApplication.translate("Elementos", u"get time", None))
        self.label_71.setText(QCoreApplication.translate("Elementos", u"timef1", None))
        self.label_72.setText(QCoreApplication.translate("Elementos", u"btnf1", None))
        self.label_7.setText(QCoreApplication.translate("Elementos", u"QDateTimeEdit", None))
        self.btng3.setText(QCoreApplication.translate("Elementos", u"get date_time", None))
        self.btng1.setText(QCoreApplication.translate("Elementos", u"get date", None))
        self.btng2.setText(QCoreApplication.translate("Elementos", u"get time", None))
        self.datimeg1_2.setText(QCoreApplication.translate("Elementos", u"sboxh1", None))
        self.label_68.setText(QCoreApplication.translate("Elementos", u"btng1", None))
        self.label_69.setText(QCoreApplication.translate("Elementos", u"btng2", None))
        self.label_70.setText(QCoreApplication.translate("Elementos", u"btng3", None))
        self.label_8.setText(QCoreApplication.translate("Elementos", u"QSpinBox", None))
        self.btnh2.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.btnh1.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.label_63.setText(QCoreApplication.translate("Elementos", u"dsboxh1", None))
        self.label_64.setText(QCoreApplication.translate("Elementos", u"sboxh1", None))
        self.label_65.setText(QCoreApplication.translate("Elementos", u"btnh1", None))
        self.label_66.setText(QCoreApplication.translate("Elementos", u"btnh2", None))
        self.label_9.setText(QCoreApplication.translate("Elementos", u"QPlainTextEdit", None))
        self.ptexti1.setPlainText(QCoreApplication.translate("Elementos", u"notas", None))
        self.btni1.setText(QCoreApplication.translate("Elementos", u"add", None))
        self.btni2.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.btni3.setText(QCoreApplication.translate("Elementos", u"clear", None))
        self.label_59.setText(QCoreApplication.translate("Elementos", u"btni1", None))
        self.label_60.setText(QCoreApplication.translate("Elementos", u"btni2", None))
        self.label_61.setText(QCoreApplication.translate("Elementos", u"btni3", None))
        self.label_62.setText(QCoreApplication.translate("Elementos", u"ptexti1", None))
        self.label_10.setText(QCoreApplication.translate("Elementos", u"QSlider", None))
        self.btnj2.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.btnj1.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.btnj3.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.label_54.setText(QCoreApplication.translate("Elementos", u"btnj2", None))
        self.label_55.setText(QCoreApplication.translate("Elementos", u"btnj3", None))
        self.label_56.setText(QCoreApplication.translate("Elementos", u"btnj1", None))
        self.label_57.setText(QCoreApplication.translate("Elementos", u"hslij1", None))
        self.label_58.setText(QCoreApplication.translate("Elementos", u"vslij1", None))
        self.label_11.setText(QCoreApplication.translate("Elementos", u"QDial", None))
        self.btnk1.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.btnk2.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.label_51.setText(QCoreApplication.translate("Elementos", u"btnk1", None))
        self.label_52.setText(QCoreApplication.translate("Elementos", u"btnk2", None))
        self.label_53.setText(QCoreApplication.translate("Elementos", u"dialk1", None))
        self.label_12.setText(QCoreApplication.translate("Elementos", u"QRadioButton", None))
        self.groupBox.setTitle(QCoreApplication.translate("Elementos", u"grupo", None))
        self.rbtnl1.setText(QCoreApplication.translate("Elementos", u"python", None))
        self.rbtnl2.setText(QCoreApplication.translate("Elementos", u"java", None))
        self.rbtnl3.setText(QCoreApplication.translate("Elementos", u"c#", None))
        self.label_48.setText(QCoreApplication.translate("Elementos", u"rbtnl1", None))
        self.label_49.setText(QCoreApplication.translate("Elementos", u"rbtnl2", None))
        self.label_50.setText(QCoreApplication.translate("Elementos", u"rbtnl3", None))
        self.label_13.setText(QCoreApplication.translate("Elementos", u"QCheckBox", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Elementos", u"grupo", None))
        self.chboxm1.setText(QCoreApplication.translate("Elementos", u"python", None))
        self.chboxm2.setText(QCoreApplication.translate("Elementos", u"java", None))
        self.chboxm3.setText(QCoreApplication.translate("Elementos", u"c#", None))
        self.label_45.setText(QCoreApplication.translate("Elementos", u"chboxm1", None))
        self.label_46.setText(QCoreApplication.translate("Elementos", u"chboxm2", None))
        self.label_47.setText(QCoreApplication.translate("Elementos", u"chboxm3", None))
        self.label_14.setText(QCoreApplication.translate("Elementos", u"QLCDNumber", None))
        self.btnn1.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.btnn2.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.label_42.setText(QCoreApplication.translate("Elementos", u"btnn1", None))
        self.label_43.setText(QCoreApplication.translate("Elementos", u"btnn2", None))
        self.label_44.setText(QCoreApplication.translate("Elementos", u"lcdnn1", None))
        self.label_15.setText(QCoreApplication.translate("Elementos", u"QListWidget", None))
        self.btno1.setText(QCoreApplication.translate("Elementos", u"add item", None))
        self.btno2.setText(QCoreApplication.translate("Elementos", u"add items", None))
        self.btno3.setText(QCoreApplication.translate("Elementos", u"clear", None))
        self.btno4.setText(QCoreApplication.translate("Elementos", u"remover item", None))
        self.label_37.setText(QCoreApplication.translate("Elementos", u"btno1", None))
        self.label_38.setText(QCoreApplication.translate("Elementos", u"btno2", None))
        self.label_39.setText(QCoreApplication.translate("Elementos", u"btno3", None))
        self.label_40.setText(QCoreApplication.translate("Elementos", u"btno4", None))
        self.label_41.setText(QCoreApplication.translate("Elementos", u"listwo1", None))
        self.label_16.setText(QCoreApplication.translate("Elementos", u"QStackedWidget", None))
        self.btnp1.setText(QCoreApplication.translate("Elementos", u"ventana 1", None))
        self.btnp2.setText(QCoreApplication.translate("Elementos", u"ventana 2", None))
        self.btnp3.setText(QCoreApplication.translate("Elementos", u"get index", None))
        self.label_113.setText(QCoreApplication.translate("Elementos", u"stwp1", None))
        self.label_114.setText(QCoreApplication.translate("Elementos", u"btnp1", None))
        self.label_115.setText(QCoreApplication.translate("Elementos", u"btnp3", None))
        self.label_116.setText(QCoreApplication.translate("Elementos", u"btnp2", None))
        self.label_17.setText(QCoreApplication.translate("Elementos", u"QTabWidget", None))
        self.btnq3.setText(QCoreApplication.translate("Elementos", u"get index", None))
        self.btnq2.setText(QCoreApplication.translate("Elementos", u"tab 2", None))
        self.btnq1.setText(QCoreApplication.translate("Elementos", u"tab 1", None))
        self.btnq4.setText(QCoreApplication.translate("Elementos", u"cambiar titulo", None))
        self.label_112.setText(QCoreApplication.translate("Elementos", u"btnq4", None))
        self.tabq1.setTabText(self.tabq1.indexOf(self.tab), QCoreApplication.translate("Elementos", u"Tab 1", None))
        self.tabq1.setTabText(self.tabq1.indexOf(self.tab_2), QCoreApplication.translate("Elementos", u"Tab 2", None))
        self.label_108.setText(QCoreApplication.translate("Elementos", u"btnq1", None))
        self.label_109.setText(QCoreApplication.translate("Elementos", u"btnq3", None))
        self.label_110.setText(QCoreApplication.translate("Elementos", u"btnq2", None))
        self.label_111.setText(QCoreApplication.translate("Elementos", u"tabq1", None))
        self.label_18.setText(QCoreApplication.translate("Elementos", u"QToolBox", None))
        self.btnr5.setText(QCoreApplication.translate("Elementos", u"cambiar titulo", None))
        self.label_107.setText(QCoreApplication.translate("Elementos", u"btnr5", None))
        self.tboxr1.setItemText(self.tboxr1.indexOf(self.page_24), QCoreApplication.translate("Elementos", u"Page 1", None))
        self.tboxr1.setItemText(self.tboxr1.indexOf(self.page_25), QCoreApplication.translate("Elementos", u"Page 2", None))
        self.tboxr1.setItemText(self.tboxr1.indexOf(self.page_26), QCoreApplication.translate("Elementos", u"Page 3", None))
        self.btnr1.setText(QCoreApplication.translate("Elementos", u"page 1", None))
        self.btnr4.setText(QCoreApplication.translate("Elementos", u"get index", None))
        self.btnr2.setText(QCoreApplication.translate("Elementos", u"page 2", None))
        self.btnr3.setText(QCoreApplication.translate("Elementos", u"page 3", None))
        self.label_102.setText(QCoreApplication.translate("Elementos", u"btnr1", None))
        self.label_103.setText(QCoreApplication.translate("Elementos", u"btnr2", None))
        self.label_104.setText(QCoreApplication.translate("Elementos", u"btnr3", None))
        self.label_105.setText(QCoreApplication.translate("Elementos", u"btnr4", None))
        self.label_106.setText(QCoreApplication.translate("Elementos", u"tboxr1", None))
        self.label_19.setText(QCoreApplication.translate("Elementos", u"QProgressBar", None))
        self.bars1.setFormat(QCoreApplication.translate("Elementos", u"%p%", None))
        self.btns1.setText(QCoreApplication.translate("Elementos", u"reset", None))
        self.btns3.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.btns2.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.label_98.setText(QCoreApplication.translate("Elementos", u"bars1", None))
        self.label_99.setText(QCoreApplication.translate("Elementos", u"btns1", None))
        self.label_100.setText(QCoreApplication.translate("Elementos", u"btns2", None))
        self.label_101.setText(QCoreApplication.translate("Elementos", u"btns3", None))
        self.label_20.setText(QCoreApplication.translate("Elementos", u"QTableWidget", None))
        ___qtablewidgetitem = self.tablet1.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Elementos", u"ID", None));
        ___qtablewidgetitem1 = self.tablet1.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Elementos", u"Nombre", None));
        ___qtablewidgetitem2 = self.tablet1.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Elementos", u"Correo", None));
        ___qtablewidgetitem3 = self.tablet1.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Elementos", u"Web", None));
        self.btnt1.setText(QCoreApplication.translate("Elementos", u"set", None))
        self.btnt2.setText(QCoreApplication.translate("Elementos", u"get", None))
        self.btnt3.setText(QCoreApplication.translate("Elementos", u"reset", None))
        self.btnt4.setText(QCoreApplication.translate("Elementos", u"delete", None))
        self.label_93.setText(QCoreApplication.translate("Elementos", u"btnt1", None))
        self.label_94.setText(QCoreApplication.translate("Elementos", u"btnt2", None))
        self.label_95.setText(QCoreApplication.translate("Elementos", u"btnt3", None))
        self.label_96.setText(QCoreApplication.translate("Elementos", u"btnt4", None))
        self.label_97.setText(QCoreApplication.translate("Elementos", u"tablet1", None))
        self.label_21.setText(QCoreApplication.translate("Elementos", u"QFontComboBox", None))
        self.btnu1.setText(QCoreApplication.translate("Elementos", u"get text", None))
        self.lblu1.setText(QCoreApplication.translate("Elementos", u"texto de prueba", None))
        self.label_117.setText(QCoreApplication.translate("Elementos", u"fcboxu1", None))
        self.label_118.setText(QCoreApplication.translate("Elementos", u"btnu1", None))
        self.label_119.setText(QCoreApplication.translate("Elementos", u"lblu1", None))
        self.label.setText(QCoreApplication.translate("Elementos", u"QPushButton", None))
        self.btna1.setText(QCoreApplication.translate("Elementos", u"cambiar nombre", None))
        self.btna2.setText(QCoreApplication.translate("Elementos", u"impresi\u00f3n en consola", None))
        self.label_91.setText(QCoreApplication.translate("Elementos", u"btna1", None))
        self.label_92.setText(QCoreApplication.translate("Elementos", u"btna2", None))
        self.label_22.setText(QCoreApplication.translate("Elementos", u"QScrollArea", None))
        self.label_120.setText(QCoreApplication.translate("Elementos", u"btnv2", None))
        self.label_121.setText(QCoreApplication.translate("Elementos", u"btnv1", None))
        self.label_23.setText(QCoreApplication.translate("Elementos", u"Texto 1", None))
        self.lineEdit.setText(QCoreApplication.translate("Elementos", u"uno", None))
        self.label_24.setText(QCoreApplication.translate("Elementos", u"Texto 2", None))
        self.lineEdit_2.setText(QCoreApplication.translate("Elementos", u"dos", None))
        self.label_25.setText(QCoreApplication.translate("Elementos", u"Texto 3", None))
        self.lineEdit_3.setText(QCoreApplication.translate("Elementos", u"tres", None))
        self.label_26.setText(QCoreApplication.translate("Elementos", u"Texto 4", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("Elementos", u"cuatro", None))
        self.label_27.setText(QCoreApplication.translate("Elementos", u"Valor 1", None))
        self.btnv1.setText(QCoreApplication.translate("Elementos", u"Arriba", None))
        self.btnv2.setText(QCoreApplication.translate("Elementos", u"Abajo", None))
        self.label_122.setText(QCoreApplication.translate("Elementos", u"sareav1", None))
        self.label_28.setText(QCoreApplication.translate("Elementos", u"QLabel", None))
        self.label_124.setText(QCoreApplication.translate("Elementos", u"btnw1", None))
        self.btnw1.setText(QCoreApplication.translate("Elementos", u"cambiar texto", None))
        self.lblw1.setText(QCoreApplication.translate("Elementos", u"Texto muestra", None))
    # retranslateUi

